services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board-game-app
    ports:
      - "3011:3011"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
        # condition: service_healthy
    volumes:
      - .:/usr/src/app
    restart: always

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Something
      - MYSQL_DATABASE=miechallenge
      - MYSQL_USER=rahul
      - MYSQL_PASSWORD=Something
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # healthcheck: 
    #   test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SELECT 1'"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    restart: always
    # command: >
    #    sh -c "apt-get update && apt-get install -y mariadb-client && exec docker-entrypoint.sh mysqld"

volumes:
  db_data:
